# fly.toml — ganti "tfidf-produk" dengan nama app kamu di Fly.io
app = "tfidf-produk"
primary_region = "sin" # Singapore — paling deket buat Indonesia

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false   # ← ini yang bikin app ga tidur!
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
